services:
  api:
    container_name: mini-project-be-api
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-project-be:compose
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3002"
    restart: unless-stopped
